---
name: Build a docker iamge and push it to AWS ECR
on: [push]
    
jobs:
  test:
    name: Build and push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Buid image 
        run: |
          docker build .



    
