---
name: Build a docker iamge and push it to AWS ECR
on:
  release: 
    types: [published]
    
jobs:
  test:
    name: Build and push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
